name: Generate Coverage
on:
  push:
    branches:
      - main
      - next

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn
      - name: Generate coverage report
        run: yarn coverage > coverage.json
      - name: Upload report
        run: node_modules/.bin/codecov --disable=gcov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
          CI: true